version: "3.8"

networks:
  monitoring-net:
    driver: bridge

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achat_db
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - monitoring-net

  app-timesheet:
    depends_on:
      - mysqldb
    image: islem2222/timesheet-devops:1.0.0
    restart: on-failure
    ports:
      - 8090:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achat_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
    networks:
      - monitoring-net

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./rules.yml:/etc/prometheus/rules.yml:ro
    ports:
      - 9091:9090
    depends_on:
      - node_exporter
      - blackbox_exporter
    networks:
      - monitoring-net

  node_exporter:
    image: prom/node-exporter
    restart: unless-stopped
    ports:
        - 9101:9100

    networks:
      - monitoring-net

  blackbox_exporter:
    image: prom/blackbox-exporter
    restart: unless-stopped
    ports:
      - 9115:9115
    networks:
      - monitoring-net

volumes:
  db:
